export const ASSETS = {
    BALLOON: 'air_balloon',
    BRIDGE: 'bridge',
    BUBBLE: 'sbubble',
    CATAPULT: 'catapult',
    CRT: 'crt',
    DUST: 'dust',
    DRAGON: 'dragon',
    ENERGY: 'energy',
    FAR_FOREST: 'bg3',
    FLAG: 'flag',
    FOREST: 'bg4',
    FRAMES: 'frames',
    GAME_OVER: 'game_over',
    GRASS: 'grass',
    HEAD: 'head',
    HEARTS: 'hearts',
    ITEMS: 'items',
    LOGO: 'chwat',
    MAP_BG: 'map_bg',
    MAP_PIECE: 'map_piece',
    MOUNTAINS: 'bg2',
    PADDLE: 'paddle',
    PLAYER: 'player',
    ROCK: 'rock',
    SKY: 'bg6',
    SLIME: 'slime',
    SPIDER_TRAP: 'spider_trap',
    SCANLINES: 'scanlines',
    SHINE: 'shine',
    SWITCH: 'switch',
    TORCH: 'torches',
    TILES: 'tiles',
    THE_END: 'end',
    WATER: 'water'
}

export const FONTS = {
    FONT_SMALL: { name: 'font_small', size: 5 },
    FONT_NORMAL: { name: 'font_normal', size: 8 },
    FONT_BIG: { name: 'font_big', size: 16 }
}
