export const ASSETS = {
    BALLOON: 'air_balloon',
    BUTTONS: 'buttons',
    COOK: 'cook',
    SLIME: 'slime',
    BUBBLE: 'sbubble',
    BRIDGE: 'bridge',
    CATAPULT: 'catapult',
    MAP_PIECE: 'map_piece',
    CRUSHER: 'crusher',
    DUST: 'dust',
    DRAGON: 'dragon',
    ENERGY: 'energy',
    FAR_FOREST: 'bg3',
    FLAG: 'flag',
    FOG: 'bg5',
    FOREST: 'bg4',
    FRAMES: 'frames',
    GRASS: 'grass',
    HEAD: 'head',
    HEARTS: 'hearts',
    ITEMS: 'items',
    LAVA: 'lava',
    LIGHTING: 'lighting',
    LOGO: 'chwat',
    MOUNTAINS: 'bg2',
    PADDLE: 'paddle',
    PLAYER: 'player',
    ROCK: 'rock',
    SKY: 'bg6',
    SPIDER_TRAP: 'spider_trap',
    SCANLINES: 'scanlines',
    SWITCH: 'switch',
    TORCH: 'torches',
    TILES: 'tiles',
    WATER: 'water',
    WITCH: 'witch'
}

export const FONTS = {
    FONT_SMALL: { name: 'font_small', size: 5},
    FONT_NORMAL: { name: 'font_normal', size: 8},
    FONT_BIG: { name: 'font_big', size: 16}
}
